#!/usr/bin/env python

"""
Interpolate between geometries.
"""

import yaml
import argparse

from psgeom import camera

example_param_file = """
# EXAMPLE PARAMETER FILE for geoterpliate.py

# the variable z_pos below is an example, you can have as many of
# these "independent" variables as you want and call them whatever
# you like! All that is required is that every "position", both
# calibration & prediction, have the same independent variables
# and every position has every variable.
#
# Special word "file" is always required. Duh.



calibration:
    files : [pos1.geom, pos2.geom]
    z_pos : [0.0, 1.0] 
    # ... (as many as you like)


# the script will write these files
prediction:
  - new_position_1
     file  : np.geom  # will be created
     z_pos : 0.5

"""




# parse
parser = argparse.ArgumentParser(description='Employ calibration geometries to'
                                             ' generate a new geometry at an'
                                             ' interpolated position.')
parser.add_argument('paramfile', default=None, required=True,
                    help='A YAML file specifying the input/output')
args = parser.parse_args()

# load parameters
f = open(args.paramfile, 'r')
params = yaml.load(f)
f.close()


calibration = params['calibration']




